const adventuregirl = [
"Dead (1).png",
"Dead (10).png",
"Dead (2).png",
"Dead (3).png",
"Dead (4).png",
"Dead (5).png",
"Dead (6).png",
"Dead (7).png",
"Dead (8).png",
"Dead (9).png",
"Idle (1).png",
"Idle (10).png",
"Idle (2).png",
"Idle (3).png",
"Idle (4).png",
"Idle (5).png",
"Idle (6).png",
"Idle (7).png",
"Idle (8).png",
"Idle (9).png",
"Jump (1).png",
"Jump (10).png",
"Jump (2).png",
"Jump (3).png",
"Jump (4).png",
"Jump (5).png",
"Jump (6).png",
"Jump (7).png",
"Jump (8).png",
"Jump (9).png",
"Melee (1).png",
"Melee (2).png",
"Melee (3).png",
"Melee (4).png",
"Melee (5).png",
"Melee (6).png",
"Melee (7).png",
"Run (1).png",
"Run (2).png",
"Run (3).png",
"Run (4).png",
"Run (5).png",
"Run (6).png",
"Run (7).png",
"Run (8).png",
"Shoot (1).png",
"Shoot (2).png",
"Shoot (3).png",
"Slide (1).png",
"Slide (2).png",
"Slide (3).png",
"Slide (4).png",
"Slide (5).png",
]
const cat = [
"Dead (1).png",
"Dead (10).png",
"Dead (2).png",
"Dead (3).png",
"Dead (4).png",
"Dead (5).png",
"Dead (6).png",
"Dead (7).png",
"Dead (8).png",
"Dead (9).png",
"Fall (1).png",
"Fall (2).png",
"Fall (3).png",
"Fall (4).png",
"Fall (5).png",
"Fall (6).png",
"Fall (7).png",
"Fall (8).png",
"Hurt (1).png",
"Hurt (10).png",
"Hurt (2).png",
"Hurt (3).png",
"Hurt (4).png",
"Hurt (5).png",
"Hurt (6).png",
"Hurt (7).png",
"Hurt (8).png",
"Hurt (9).png",
"Idle (1).png",
"Idle (10).png",
"Idle (2).png",
"Idle (3).png",
"Idle (4).png",
"Idle (5).png",
"Idle (6).png",
"Idle (7).png",
"Idle (8).png",
"Idle (9).png",
"Jump (1).png",
"Jump (2).png",
"Jump (3).png",
"Jump (4).png",
"Jump (5).png",
"Jump (6).png",
"Jump (7).png",
"Jump (8).png",
"Run (1).png",
"Run (2).png",
"Run (3).png",
"Run (4).png",
"Run (5).png",
"Run (6).png",
"Run (7).png",
"Run (8).png",
"Slide (1).png",
"Slide (10).png",
"Slide (2).png",
"Slide (3).png",
"Slide (4).png",
"Slide (5).png",
"Slide (6).png",
"Slide (7).png",
"Slide (8).png",
"Slide (9).png",
"Walk (1).png",
"Walk (10).png",
"Walk (2).png",
"Walk (3).png",
"Walk (4).png",
"Walk (5).png",
"Walk (6).png",
"Walk (7).png",
"Walk (8).png",
"Walk (9).png",
]
const dino = [
"Dead (1).png",
"Dead (2).png",
"Dead (3).png",
"Dead (4).png",
"Dead (5).png",
"Dead (6).png",
"Dead (7).png",
"Dead (8).png",
"Idle (1).png",
"Idle (10).png",
"Idle (2).png",
"Idle (3).png",
"Idle (4).png",
"Idle (5).png",
"Idle (6).png",
"Idle (7).png",
"Idle (8).png",
"Idle (9).png",
"Jump (1).png",
"Jump (10).png",
"Jump (11).png",
"Jump (12).png",
"Jump (2).png",
"Jump (3).png",
"Jump (4).png",
"Jump (5).png",
"Jump (6).png",
"Jump (7).png",
"Jump (8).png",
"Jump (9).png",
"Run (1).png",
"Run (2).png",
"Run (3).png",
"Run (4).png",
"Run (5).png",
"Run (6).png",
"Run (7).png",
"Run (8).png",
"Walk (1).png",
"Walk (10).png",
"Walk (2).png",
"Walk (3).png",
"Walk (4).png",
"Walk (5).png",
"Walk (6).png",
"Walk (7).png",
"Walk (8).png",
"Walk (9).png",
]
const dog = [
    "Dead (1).png",
    "Dead (10).png",
    "Dead (2).png",
    "Dead (3).png",
    "Dead (4).png",
    "Dead (5).png",
    "Dead (6).png",
    "Dead (7).png",
    "Dead (8).png",
    "Dead (9).png",
    "Fall (1).png",
    "Fall (2).png",
    "Fall (3).png",
    "Fall (4).png",
    "Fall (5).png",
    "Fall (6).png",
    "Fall (7).png",
    "Fall (8).png",
    "Hurt (1).png",
    "Hurt (10).png",
    "Hurt (2).png",
    "Hurt (3).png",
    "Hurt (4).png",
    "Hurt (5).png",
    "Hurt (6).png",
    "Hurt (7).png",
    "Hurt (8).png",
    "Hurt (9).png",
    "Idle (1).png",
    "Idle (10).png",
    "Idle (2).png",
    "Idle (3).png",
    "Idle (4).png",
    "Idle (5).png",
    "Idle (6).png",
    "Idle (7).png",
    "Idle (8).png",
    "Idle (9).png",
    "Jump (1).png",
    "Jump (2).png",
    "Jump (3).png",
    "Jump (4).png",
    "Jump (5).png",
    "Jump (6).png",
    "Jump (7).png",
    "Jump (8).png",
    "Run (1).png",
    "Run (2).png",
    "Run (3).png",
    "Run (4).png",
    "Run (5).png",
    "Run (6).png",
    "Run (7).png",
    "Run (8).png",
    "Slide (1).png",
    "Slide (10).png",
    "Slide (2).png",
    "Slide (3).png",
    "Slide (4).png",
    "Slide (5).png",
    "Slide (6).png",
    "Slide (7).png",
    "Slide (8).png",
    "Slide (9).png",
    "Walk (1).png",
    "Walk (10).png",
    "Walk (2).png",
    "Walk (3).png",
    "Walk (4).png",
    "Walk (5).png",
    "Walk (6).png",
    "Walk (7).png",
    "Walk (8).png",
    "Walk (9).png",    
]
const knight = [
    "Attack (1).png",
    "Attack (10).png",
    "Attack (2).png",
    "Attack (3).png",
    "Attack (4).png",
    "Attack (5).png",
    "Attack (6).png",
    "Attack (7).png",
    "Attack (8).png",
    "Attack (9).png",
    "Dead (1).png",
    "Dead (10).png",
    "Dead (2).png",
    "Dead (3).png",
    "Dead (4).png",
    "Dead (5).png",
    "Dead (6).png",
    "Dead (7).png",
    "Dead (8).png",
    "Dead (9).png",
    "Idle (1).png",
    "Idle (10).png",
    "Idle (2).png",
    "Idle (3).png",
    "Idle (4).png",
    "Idle (5).png",
    "Idle (6).png",
    "Idle (7).png",
    "Idle (8).png",
    "Idle (9).png",
    "Jump (1).png",
    "Jump (10).png",
    "Jump (2).png",
    "Jump (3).png",
    "Jump (4).png",
    "Jump (5).png",
    "Jump (6).png",
    "Jump (7).png",
    "Jump (8).png",
    "Jump (9).png",
    "JumpAttack (1).png",
    "JumpAttack (10).png",
    "JumpAttack (2).png",
    "JumpAttack (3).png",
    "JumpAttack (4).png",
    "JumpAttack (5).png",
    "JumpAttack (6).png",
    "JumpAttack (7).png",
    "JumpAttack (8).png",
    "JumpAttack (9).png",
    "Run (1).png",
    "Run (10).png",
    "Run (2).png",
    "Run (3).png",
    "Run (4).png",
    "Run (5).png",
    "Run (6).png",
    "Run (7).png",
    "Run (8).png",
    "Run (9).png",
    "Walk (1).png",
    "Walk (10).png",
    "Walk (2).png",
    "Walk (3).png",
    "Walk (4).png",
    "Walk (5).png",
    "Walk (6).png",
    "Walk (7).png",
    "Walk (8).png",
    "Walk (9).png",    
]
const plane = [
    "Shoot (5).png",
    "Dead (1).png",
    "Fly (1).png",
    "Fly (2).png",
    "Shoot (1).png",
    "Shoot (2).png",
    "Shoot (3).png",
    "Shoot (4).png",    
]
const redhat = [
    "Dead (1).png",
    "Dead (10).png",
    "Dead (2).png",
    "Dead (3).png",
    "Dead (4).png",
    "Dead (5).png",
    "Dead (6).png",
    "Dead (7).png",
    "Dead (8).png",
    "Dead (9).png",
    "Hurt (1).png",
    "Hurt (2).png",
    "Hurt (3).png",
    "Hurt (4).png",
    "Hurt (5).png",
    "Hurt (6).png",
    "Hurt (7).png",
    "Hurt (8).png",
    "Idle (1).png",
    "Idle (10).png",
    "Idle (2).png",
    "Idle (3).png",
    "Idle (4).png",
    "Idle (5).png",
    "Idle (6).png",
    "Idle (7).png",
    "Idle (8).png",
    "Idle (9).png",
    "Jump (1).png",
    "Jump (10).png",
    "Jump (11).png",
    "Jump (12).png",
    "Jump (2).png",
    "Jump (3).png",
    "Jump (4).png",
    "Jump (5).png",
    "Jump (6).png",
    "Jump (7).png",
    "Jump (8).png",
    "Jump (9).png",
    "Run (1).png",
    "Run (2).png",
    "Run (3).png",
    "Run (4).png",
    "Run (5).png",
    "Run (6).png",
    "Run (7).png",
    "Run (8).png",
    "Slide (1).png",
    "Slide (2).png",
    "Slide (3).png",
    "Slide (4).png",
    "Slide (5).png",    
]
const robot = [
    "Dead (1).png",
    "Dead (10).png",
    "Dead (2).png",
    "Dead (3).png",
    "Dead (4).png",
    "Dead (5).png",
    "Dead (6).png",
    "Dead (7).png",
    "Dead (8).png",
    "Dead (9).png",
    "Idle (1).png",
    "Idle (10).png",
    "Idle (2).png",
    "Idle (3).png",
    "Idle (4).png",
    "Idle (5).png",
    "Idle (6).png",
    "Idle (7).png",
    "Idle (8).png",
    "Idle (9).png",
    "Jump (1).png",
    "Jump (10).png",
    "Jump (2).png",
    "Jump (3).png",
    "Jump (4).png",
    "Jump (5).png",
    "Jump (6).png",
    "Jump (7).png",
    "Jump (8).png",
    "Jump (9).png",
    "JumpMelee (1).png",
    "JumpMelee (2).png",
    "JumpMelee (3).png",
    "JumpMelee (4).png",
    "JumpMelee (5).png",
    "JumpMelee (6).png",
    "JumpMelee (7).png",
    "JumpMelee (8).png",
    "JumpShoot (1).png",
    "JumpShoot (2).png",
    "JumpShoot (3).png",
    "JumpShoot (4).png",
    "JumpShoot (5).png",
    "Melee (1).png",
    "Melee (2).png",
    "Melee (3).png",
    "Melee (4).png",
    "Melee (5).png",
    "Melee (6).png",
    "Melee (7).png",
    "Melee (8).png",
    "Run (1).png",
    "Run (2).png",
    "Run (3).png",
    "Run (4).png",
    "Run (5).png",
    "Run (6).png",
    "Run (7).png",
    "Run (8).png",
    "RunShoot (1).png",
    "RunShoot (2).png",
    "RunShoot (3).png",
    "RunShoot (4).png",
    "RunShoot (5).png",
    "RunShoot (6).png",
    "RunShoot (7).png",
    "RunShoot (8).png",
    "RunShoot (9).png",
    "Shoot (1).png",
    "Shoot (2).png",
    "Shoot (3).png",
    "Shoot (4).png",
    "Slide (1).png",
    "Slide (10).png",
    "Slide (2).png",
    "Slide (3).png",
    "Slide (4).png",
    "Slide (5).png",
    "Slide (6).png",
    "Slide (7).png",
    "Slide (8).png",
    "Slide (9).png",    
]
const scratch = [
"abby-a.svg",
"abby-b.svg",
"abby-c.svg",
"abby-d.svg",
"apple.svg",
"avery-a.svg",
"avery-b.svg",
"avery_walking-a.svg",
"avery_walking-b.svg",
"avery_walking-c.svg",
"avery_walking-d.svg",
"ball-a.svg",
"ball-b.svg",
"ball-c.svg",
"ball-d.svg",
"ball-e.svg",
"ball-soccer.svg",
"balloon1-a.svg",
"balloon1-b.svg",
"balloon1-c.svg",
"bananas.svg",
"baseball.svg",
"basketball.svg",
"bass.svg",
"bat1-a.png",
"bat1-b.png",
"bat2-a.png",
"bat2-b.png",
"beachball.svg",
"bear1-a.svg",
"bear1-b.svg",
"bear2-a.svg",
"bear2-b.svg",
"beetle.svg",
"bell1.svg",
"bells-a.svg",
"bells-b.svg",
"bowl-a.svg",
"bowtie-a.svg",
"bowtie-b.svg",
"breakdancer1-a.png",
"breakdancer1-b.png",
"breakdancer1-c.png",
"building-a.svg",
"building-b.svg",
"building-c.svg",
"building-d.svg",
"building-e.svg",
"building-f.svg",
"building-g.svg",
"building-h.svg",
"building-i.svg",
"building-j.svg",
"bus.png",
"cake-a.svg",
"cake-b.svg",
"candle1-a.svg",
"candle1-b.svg",
"candles1.svg",
"candles2.svg",
"car-bug.png",
"cheesy-puffs.png",
"cloud-a.svg",
"cloud-b.svg",
"cloud-c.svg",
"cloud-d.svg",
"cloud.svg",
"convertible1.png",
"convertible2.png",
"convertible3.svg",
"cowbell.svg",
"crab-a.svg",
"crab-b.svg",
"cymbal-a.svg",
"cymbal-b.svg",
"derec01.png",
"derec02.png",
"derec03.png",
"derec04.png",
"derec05.png",
"derec06.png",
"devin-a.svg",
"devin-b.svg",
"devin-c.svg",
"devin-d.svg",
"dinosaur1-a.svg",
"dinosaur1-b.svg",
"dinosaur1-c.svg",
"dinosaur1-d.svg",
"dinosaur1-e.svg",
"dinosaur1-f.svg",
"dinosaur1-g.svg",
"dinosaur2-a.svg",
"dinosaur2-b.svg",
"dinosaur3.svg",
"diver1.svg",
"diver2.svg",
"dog1-a.png",
"dog1-a.svg",
"dog1-b.png",
"dog1-b.svg",
"dog2-a.png",
"dog2-a.svg",
"dog2-b.png",
"dog2-b.svg",
"dog2-c.png",
"dog2-c.svg",
"donut.svg",
"dove1-a.svg",
"dove1-b.svg",
"dove2-a.svg",
"dove2-b.svg",
"dragon1-a.png",
"dragon1-a.svg",
"dragon1-b.png",
"dragon1-b.svg",
"dragon2.gif",
"drum1-a.svg",
"drum1-b.svg",
"drum2-a.svg",
"drum2-b.svg",
"drums_conga-a.svg",
"drums_conga-b.svg",
"drum_bass-a.svg",
"drum_bass-b.svg",
"drum_snare-a.svg",
"drum_snare-b.svg",
"duck.svg",
"earth.svg",
"elephant-a_.svg",
"elephant-b_.svg",
"fire_hydrant.png",
"fish1.svg",
"fish2.svg",
"fish3.svg",
"flower_shape.svg",
"football_running.png",
"football_standing.png",
"fortunecookie.png",
"fox.svg",
"frog.svg",
"fruitsalad.svg",
"fruit_platter.png",
"ghost1_.svg",
"ghost2-a.svg",
"ghost2-b.svg",
"ghoul-a.svg",
"ghoul-b.svg",
"gift-a.svg",
"gift-b.svg",
"girl1-standing.gif",
"girl1-walking.gif",
"girl2-shouting.gif",
"girl2-standing.gif",
"girl3-basketball.gif",
"girl3-running.gif",
"girl3-standing.gif",
"glasses.svg",
"glass_water-a.svg",
"glass_water-b.svg",
"green_flag.svg",
"guitar bass.svg",
"guitar.svg",
"guitar_bass.svg",
"guitar_electric.svg",
"hannah-a.png",
"hannah-b.png",
"hannah-c.png",
"Hat.svg",
"hat_beanie.svg",
"hat_party2-a.svg",
"hat_winter.svg",
"hat_wizard.svg",
"headband.svg",
"heart_code.svg",
"heart_face.svg",
"heart_love_it.svg",
"heart_purple.svg",
"heart_red.svg",
"heart_smile.svg",
"heart_sweet.svg",
"helicopter.png",
"hippo1-a.svg",
"hippo1-b.svg",
"holly1.svg",
"holly2.svg",
"home_button.svg",
"horse1-a.svg",
"horse1-b.svg",
"jahrd01.png",
"jahrd02.png",
"jahrd03.png",
"jahrd04.png",
"jahrd05.png",
"jahrd06.png",
"jaime-a.png",
"jaime-b.png",
"jaime_walking-a.png",
"jaime_walking-b.png",
"jaime_walking-c.png",
"jaime_walking-d.png",
"jaime_walking-e.png",
"jamet01.png",
"jamet02.png",
"jamet03.png",
"jamet04.png",
"jamet05.png",
"jamet06-wall.png",
"jamet06.png",
"jay.gif",
"jeans-a.svg",
"jeans-b.svg",
"jodi.gif",
"kai-a.png",
"kai-b.png",
"key.svg",
"keyboard-a.svg",
"keyboard-b.svg",
"keyboard-c.svg",
"keyboard-d.svg",
"knight.svg",
"ladybug2-a.svg",
"ladybug2-b.svg",
"ladybug2.svg",
"lamp.png",
"laptop.svg",
"lightning.svg",
"lion-a.svg",
"lion-b.svg",
"lioness.svg",
"magiccarpet.png",
"magicwand.svg",
"marble-building.png",
"marissa-crouching.gif",
"marissa-sitting.gif",
"marissa.gif",
"maya.png",
"microphone.svg",
"microphonestand.svg",
"monkey1-a.svg",
"monkey1-b.svg",
"monkey2-a.svg",
"monkey2-b.svg",
"monkey2-c.svg",
"mori.png",
"mouse1-a.svg",
"mouse1-b.svg",
"muffin-a.svg",
"muffin-b.svg",
"octopus-a.svg",
"octopus-b.svg",
"orange.svg",
"orange2-a.svg",
"orange2-b.svg",
"orange2-c.svg",
"paddle.svg",
"palmtree.gif",
"parrot-a.svg",
"parrot-b.svg",
"parrot2-a.svg",
"parrot2-b.svg",
"partyhat1.svg",
"paul.gif",
"pencil-a.svg",
"pencil-b.svg",
"penguin1.svg",
"penguin1_talk-a.svg",
"penguin1_talk-b.svg",
"penguin2.svg",
"penguin2_talk-a.svg",
"penguin2_talk-b.svg",
"penguin3-a.svg",
"penguin3-b.svg",
"penguin3-c.svg",
"piano.svg",
"planet2.svg",
"prince.svg",
"princess.svg",
"rainbow.svg",
"referee.gif",
"reindeer.svg",
"robot1.svg",
"rocks.svg",
"rory.png",
"ruby-a.png",
"ruby-b.png",
"sail-boat.png",
"sam.gif",
"saxophone-a.svg",
"saxophone-b.svg",
"scarf1.svg",
"scarf2.svg",
"shark-a_.svg",
"shark-b_.svg",
"shark-c_.svg",
"shirt-a.svg",
"shirt-b.svg",
"shirt2-a.svg",
"shirt2-a2.svg",
"shirt_blouse.svg",
"shirt_collar-a.svg",
"shirt_collar-b.svg",
"shirt_collar-c.svg",
"shoes1.svg",
"shoes2.svg",
"Singer1.svg",
"skates.svg",
"snowflake.svg",
"snowman.svg",
"spaceship-a.svg",
"spaceship-b.svg",
"speaker.svg",
"squirrel1.png",
"star1.svg",
"star2.svg",
"star3-a.svg",
"star3-b.svg",
"starfish-a.svg",
"starfish-b_.svg",
"stop.svg",
"street-cleaner-mit.png",
"sun.svg",
"sunglasses1.svg",
"sunglasses2.svg",
"tabla-a.svg",
"tabla-b.svg",
"taco-a.svg",
"taco-b.svg",
"tennisball.png",
"text awesome.svg",
"text Halloween.svg",
"text_awesome.svg",
"text_Halloween.svg",
"trampoline.png",
"tree-lights-a.svg",
"tree-lights-b.svg",
"tree1.svg",
"tree2.svg",
"trees-a.svg",
"trees-b.svg",
"trombone-a.svg",
"trombone-b.svg",
"trumpet-a.svg",
"trumpet-a2.svg",
"turtle01_colour.png",
"turtle02_colour_resized.png",
"turtle03.png",
"turtle04.png",
"turtle05.png",
"turtle06.png",
"ukulele.svg",
"umbrella.png",
"unicorn.svg",
"unicorn1.png",
"vest-a.svg",
"vest-b.svg",
"wanda.svg",
"watermelon-a.svg",
"watermelon-b.svg",
"watermelon-c.svg",
"witch.svg",
"wizard.svg",
"wizard1.svg",
"wizard2.svg",
"zara-a.png",
"zara-b.png",
]
const temple = [
    "Dead__000.png",
    "Dead__001.png",
    "Dead__002.png",
    "Dead__003.png",
    "Dead__004.png",
    "Dead__005.png",
    "Dead__006.png",
    "Dead__007.png",
    "Dead__008.png",
    "Dead__009.png",
    "Idle__000.png",
    "Idle__001.png",
    "Idle__002.png",
    "Idle__003.png",
    "Idle__004.png",
    "Idle__005.png",
    "Idle__006.png",
    "Idle__007.png",
    "Idle__008.png",
    "Idle__009.png",
    "Jump__000.png",
    "Jump__001.png",
    "Jump__002.png",
    "Jump__003.png",
    "Jump__004.png",
    "Jump__005.png",
    "Jump__006.png",
    "Jump__007.png",
    "Jump__008.png",
    "Jump__009.png",
    "Run__000.png",
    "Run__001.png",
    "Run__002.png",
    "Run__003.png",
    "Run__004.png",
    "Run__005.png",
    "Run__006.png",
    "Run__007.png",
    "Run__008.png",
    "Run__009.png",
    "Slide__000.png",
    "Slide__001.png",
    "Slide__002.png",
    "Slide__003.png",
    "Slide__004.png",
    "Slide__005.png",
    "Slide__006.png",
    "Slide__007.png",
    "Slide__008.png",
    "Slide__009.png",     
]
export default {
    adventuregirl,cat,dino,dog,knight,plane,redhat,robot,scratch,temple
}